// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Repository.MSSQL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration1));
        
        string IMigrationMetadata.Id
        {
            get { return "201709251628504_migration1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
