// <auto-generated />
namespace Repository.MSSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration7));
        
        string IMigrationMetadata.Id
        {
            get { return "201712031554489_migration7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
